### ISSUE TITLE
Program doesn't fully close

### ISSUE THREAD

**Issue by mobilegmYT** [SpacingBat3/nativefier-discord-arm#2]
Hello.
I am currently running TwisterOS, and when I close the program, the window closes, but the process is still open in task manager. Is there a way to make it so when I close the window, it fully closes the program?

**Comment by SpacingBat3** [comment]
Have you tried running the binary trough the `discord` shell script with `--no-tray` option? This should disable the tray functionality and closing the window should kill the app then.

**Comment by SpacingBat3** [comment]
For more parameters you can also type: `discord -h`.

**Comment by SpacingBat3** [comment]
Ok, as this thread seems no longer being active and I don't see any issues there at all, I'm closing it.
If anyone has still same issue, you can @ping me there to reopen this.
